#pragma once

#ifndef _IOCTLS_H
#define _IOCTLS_H

#define IOCTL_LOAD_SYMBOLS_TABLE        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LOAD_DEBUGGER_STATE       CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LOAD_PROTECT_OBJ_DATA     CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_LOAD_DEBUGGER_DATA        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_CREATE_REMOTE_THREAD      CTL_CODE(FILE_DEVICE_UNKNOWN, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_HARDWARE_BREAKPOINT            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_GET_PROCESS_INFO          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TL_BLOCK_RESUME_THREAD          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DEL_HARDWARE_BREAKPOINT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_SOFTWARE_BREAKPOINT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_DEL_SOFTWARE_BREAKPOINT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_READ_SOFTWARE_BREAKPOINT          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)

// V1 remains available to deployed clients.  New code uses V2, whose IOCTL
// access bits require an explicitly read/write device handle.  The bridge
// drivers accept both generations while the old front ends are retired.
#define UNREALDBG_IOCTL_SECURE_ACCESS            (FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_LOAD_SYMBOLS_TABLE_V2              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_LOAD_DEBUGGER_STATE_V2             CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_LOAD_PROTECT_OBJ_DATA_V2           CTL_CODE(FILE_DEVICE_UNKNOWN, 0x902, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_LOAD_DEBUGGER_DATA_V2              CTL_CODE(FILE_DEVICE_UNKNOWN, 0x903, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_CREATE_REMOTE_THREAD_V2            CTL_CODE(FILE_DEVICE_UNKNOWN, 0x904, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_SET_HARDWARE_BREAKPOINT_V2         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x905, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_GET_PROCESS_INFO_V2                CTL_CODE(FILE_DEVICE_UNKNOWN, 0x906, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_TL_BLOCK_RESUME_THREAD_V2          CTL_CODE(FILE_DEVICE_UNKNOWN, 0x907, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_DEL_HARDWARE_BREAKPOINT_V2         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x908, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_SET_SOFTWARE_BREAKPOINT_V2         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x909, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_DEL_SOFTWARE_BREAKPOINT_V2         CTL_CODE(FILE_DEVICE_UNKNOWN, 0x90A, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)
#define IOCTL_READ_SOFTWARE_BREAKPOINT_V2        CTL_CODE(FILE_DEVICE_UNKNOWN, 0x90B, METHOD_BUFFERED, UNREALDBG_IOCTL_SECURE_ACCESS)

#endif // !_IOCTLS_H
